import {
  Images1a,
  Images1,
  Images22,
  Images2,
  Images33,
  Images3,
  Images44,
  Images4,
  Images55,
  Images5,
  Images66,
  Images6,
  Images77,
  Images88,
  Images8,
  Images99,
  ImagesCasts1,
  ImagesCasts2,
  ImagesCasts3,
  ImagesCasts4,
} from "@/public/assets";

export const movieList = [
  {
    id: 1,
    mediaType: "movie",
    title: "Movie Title",
    description: "Lorem Ipsum is simply dummy text of the printing and types",
    posterPath: Images1a,
    coverPath: Images1,
    genreIds: [],
    seasons: [],
  },
  {
    id: 2,
    mediaType: "movie",
    title: "Movie Title",
    description: "Lorem Ipsum is simply dummy text of the printing and types",
    posterPath: Images22,
    coverPath: Images2,
    genreIds: [],
    seasons: [
      {
        id: 1,
        filmName: "Season.filmName",
        name: "season.name",
        posterPath: Images1a,
        seasonNumber: 1,
        airDate: "15/10/2022",
        episodes: [],
      },
      {
        id: 2,
        filmName: "Season.filmName",
        name: "season.name",
        posterPath: Images1a,
        seasonNumber: 1,
        airDate: "15/12/2022",
        episodes: [],
      },
    ],
  },
  {
    id: 3,
    mediaType: "movie",
    title: "Movie Title",
    description: "Lorem Ipsum is simply dummy text of the printing and types",
    posterPath: Images33,
    coverPath: Images3,
    genreIds: [],
    seasons: [],
  },
  {
    id: 4,
    mediaType: "movie",
    title: "Movie Title",
    description: "Lorem Ipsum is simply dummy text of the printing and types",
    posterPath: Images44,
    coverPath: Images4,
    genreIds: [],
    seasons: [],
  },
  {
    id: 5,
    mediaType: "movie",
    title: "Movie Title",
    description: "Lorem Ipsum is simply dummy text of the printing and types",
    posterPath: Images55,
    coverPath: Images5,
    genreIds: [],
    seasons: [],
  },
  {
    id: 6,
    mediaType: "movie",
    title: "Movie Title",
    description: "Lorem Ipsum is simply dummy text of the printing and types",
    posterPath: Images55,
    coverPath: Images5,
    genreIds: [],
    seasons: [],
  },
  {
    id: 7,
    mediaType: "tv",
    title: "Movie Title",
    description: "Lorem Ipsum is simply dummy text of the printing and types",
    posterPath: Images44,
    coverPath: Images4,
    genreIds: [],
    seasons: [],
  },
];
export const tvList = [
  {
    id: 1,
    mediaType: "tv",
    title: "Movie Title",
    description: "Lorem Ipsum is simply dummy text of the printing and types",
    posterPath: Images66,
    coverPath: Images6,
    genreIds: [],
    seasons: [
      {
        id: 1,
        filmName: "Season.filmName",
        name: "season.name",
        posterPath: Images1a,
        seasonNumber: 1,
        airDate: "15/10/2022",
        episodes: [],
      },
      {
        id: 2,
        filmName: "Season.filmName",
        name: "season.name",
        posterPath: Images1a,
        seasonNumber: 1,
        airDate: "15/12/2022",
        episodes: [],
      },
    ],
  },
  {
    id: 2,
    mediaType: "tv",
    title: "Movie Title",
    description: "Lorem Ipsum is simply dummy text of the printing and types",
    posterPath: Images77,
    coverPath: Images3,
    genreIds: [],
    seasons: [],
  },
  {
    id: 3,
    mediaType: "tv",
    title: "Movie Title",
    description: "Lorem Ipsum is simply dummy text of the printing and types",
    posterPath: Images88,
    coverPath: Images8,
    genreIds: [],
    seasons: [],
  },
  {
    id: 4,
    mediaType: "tv",
    title: "Movie Title",
    description: "Lorem Ipsum is simply dummy text of the printing and types",
    posterPath: Images99,
    coverPath: Images4,
    genreIds: [],
    seasons: [],
  },
  //TODO:
  {
    id: 5,
    mediaType: "tv",
    title: "Movie Title",
    description: "Lorem Ipsum is simply dummy text of the printing and types",
    posterPath: Images55,
    coverPath: Images5,
    genreIds: [],
    seasons: [],
  },
  {
    id: 6,
    mediaType: "tv",
    title: "Movie Title",
    description: "Lorem Ipsum is simply dummy text of the printing and types",
    posterPath: Images55,
    coverPath: Images5,
    genreIds: [],
    seasons: [],
  },
];

export const castList = [
  {
    id: 1,
    name: "Maldini Morgan",
    characterName: "The MOI",
    profilePath: ImagesCasts1,
  },
  {
    id: 1,
    name: "Maldini Morgan",
    characterName: "The MOI",
    profilePath: ImagesCasts2,
  },
  {
    id: 1,
    name: "Maldini Morgan",
    characterName: "The MOI",
    profilePath: ImagesCasts3,
  },
  {
    id: 1,
    name: "Maldini Morgan",
    characterName: "The MOI",
    profilePath: ImagesCasts4,
  },
];

export const genreList = [
  {
    id: 1,
    name: "Maldini Morgan",
  },
  {
    id: 1,
    name: "Maldini Morgan",
  },
  {
    id: 1,
    name: "Maldini Morgan",
  },
  {
    id: 1,
    name: "Maldini Morgan",
  },
];

export const detailInformation = {
  id: 1,
  filmName: "journey to the west",
  name: "Journey To The West",
  posterPath: Images2,
  seasonNumber: 1,
  airDate: "15/02/2021",
  episodes: [
    {
      id: 1,
      title: "Journey starts",
      overview: "episode.overview",
      airDate: "15/02/2021",
      stillPath: "",
      episodeNumber: 1,
    },
    {
      id: 2,
      title: "Journey Goes",
      overview: "episode.overview",
      airDate: "15/02/2021",
      stillPath: "",
      episodeNumber: 1,
    },
  ],
};

export const trailerList = [
  { id: 1, key: "1234" },
  { id: 2, key: "1234" },
  { id: 3, key: "1234" },
  { id: 4, key: "1234" },
  { id: 5, key: "1234" },
];
